### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by Bekt** [docker/python-dockercloud#7]
The library doesn't seem to work with python3. A lot of people have moved away from python2, so it'd be nice to add support for python3 to take advantage of the library.

$ venv3/bin/python runserver.py                                                   01:28:34
WARNING:werkzeug: * Debugger is active!

```
Python 3.5.1 (default, Dec 26 2015, 18:11:22)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import dockercloud
>>>
>>> dockercloud.Action.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv3/lib/python3.5/site-packages/dockercloud/api/base.py", line 149, in list
    json = send_request('GET', detail_uri, params=kwargs)
  File ".../venv3/lib/python3.5/site-packages/dockercloud/api/http.py", line 37, in send_request
    url = urljoin(dockercloud.rest_host.rstrip("/"), path.strip("/").encode("ascii", "ignore"))
  File ".../python3.5/urllib/parse.py", line 415, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File ".../python3.5/urllib/parse.py", line 111, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

**Comment by Midnighter** [comment]
Same experience for me, I put it in a [forum post](https://forums.docker.com/t/python-dockercloud-environment-variables-unusable-in-python-3/28011/2). Issue occurs with environment variables as well as with setting the relevant attributes.

**Comment by penkin** [comment]
Any fix or work around for this?

**Comment by Midnighter** [comment]
There are some open pull requests that look promising...

**Comment by penkin** [comment]
@Midnighter Also added a PR now as well #28. Tests pass in both Python2 and 3. Will see if it gets accepted.

**Comment by brgirgis** [comment]
Any update about this issue? Please let me know how I could help to accelerate any advancement toward a solution.

**Comment by mbdevpl** [comment]
I second this! PR #29 seems good.

My suggested workaround for the impatient:

```
pip3 install git+https://github.com/penkin/python-dockercloud
```

This will install the py3-compatible version.

**Comment by mbdevpl** [comment]
Oops, just noticed that this whole thing is deprecated...
